import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './nav/Header'
import Footer from './nav/Footer'
import RecoilRootProvider from './recoilRootProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'WE-NMIXX',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ko">
            <body className={inter.className}>
                <RecoilRootProvider>
                    <Header />
                    {children}
                    <Footer />
                </RecoilRootProvider>
            </body>
        </html>
    )
}
