import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './nav/Header'
import Footer from './nav/Footer'
import RecoilRootProvider from './recoilRootProvider'
import {
    useQuery,
    useMutation,
    useQueryClient,
    QueryClient,
    QueryClientProvider,
  } from '@tanstack/react-query'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'WE-NMIXX',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    // const queryClient = new QueryClient({
    //     defaultOptions:{
    //         queries:{
    //             staleTime:1000*60,
    //             retry:1,
    //         },
    //         mutations:{
    //             retry:1
    //         }
    //     }
    // });
    return (
        <html lang="ko">
            <body className={inter.className}>
            {/* <QueryClientProvider client={queryClient}> */}
                <RecoilRootProvider>
                    <Header />
                    {children}
                    <Footer />
                </RecoilRootProvider>
            {/* </QueryClientProvider> */}
            </body>
        </html>
    )
}
